transcom/mymove-docs

docusaurus.config.js
package.json
yarn.lock

I added the [`redocusaurus` plugin](https://github.com/rohit-gohri/redocusaurus) to our site so that we can display the ReDoc for our APIs here. To see it, please start up the app locally and click on the "APIs" dropdown in the top navbar:
```sh
yarn install
yarn start
```
1. Open your terminal/command line. 
2. Clone the repo onto your machine: 
```
git clone https://github.com/transcom/mymove-docs.git
```
- If you get a bizarre error about "xcurl" or something, try: `xcode-select --install` and run through the full installation of the MacOS command line tools.
- If you need to install `git`, please follow these instructions: https://git-scm.com/download/mac
3. Change into the repo directory: `cd mymove-docs`
```
cd mymove-docs
```
4. Checkout this branch:
```
git checkout …
```

Add Redocusaurus plugin for our APIs

---

docusaurus.config.js
package.json
yarn.lock

I've implemented a plugin to add a local search to our docs: https://github.com/cmfcmf/docusaurus-search-local. This does not require us to have our site indexed in Algolia, and no part of this is hosted on an external server. Just a simple lil search that looks at our static build files.
Please follow the instructions in the README to get set up generally: https://github.com/transcom/mymove-docs#running-locally-on-macos.
Once you checkout this branch (`git checkout add-search-plugin`), instead of `yarn start`, please run:
```sh
yarn build
yarn serve
```
Then open the local link (probably http://localhost:3000/mymove-docs/) and try to search for things!

Add a local search plugin

---

README.md

This documentation exists outside of the Docusaurus site because it's
about configuring this site. I think eventually though it may exist
inside of the Docusaurus site under a directory named `Meta` or
something similar as it's about how to operate and maintain this
website.
This came up in our last Prime API Documentation meeting, and I'm 
completing it as part of the action items in that meeting. I'm tagging 
folks that were in this meeting for review.

Add in documentation for how to use Redocusaurus

---

README.md
docs/dev/tools/redocusaurus.md

I'm doing this because I found that working with Swagger and
Redocusaurus locally isn't difficult, but it is complex enough to have
documentation on.
Apologies in advance for the changes to the README.md file. I will
highlight the only change to that document that I made in a comment.
The other changes are the removal of empty spaces which my editor
does automatically.

Give Redocusaurus its own page

---

src/components/prism-golang.js
src/theme/prism-include-languages.js

Currently, Docusaurus, by way of PrismJS, only supports the `go` alias
for syntax highlighting code blocks. For example, this will result in
the code being highlighted:
```
```go
```
but this will not:
```
```golang
```
In my case, I use Sublime Text, and the Markdown plugin I use only
highlights the code in my editor using the `golang` alias. We also have
many instances of the `golang` alias in the code blocks in this repo
because that's what we used in the GitHub Wiki.
PrismJS allows adding aliases to existing languages, but that would
require submitting a PR to the Prism repo, and I'm not sure how long it
would take for them to merge it.
Alternatively, Docusaurus allows you to define additional languages,
which is easy, and is what I did in this PR. Per the instructions, I ran
```
yarn …
```

Add support for golang alias in code blocks

---

docs/tools/cicd/happo.md

This documentation addresses the needs in ticket [10281](https://dp3.atlassian.net/browse/MB-10281). It adds instructions on what to do when Happo errors occur in the CI Process

MB-10281 Add Happo Page to Docs

---

docs/backend/guides/how-to/manage-golang-with-asdf.md

While trying to run the standalone ato-linter tool I was having what looked like go build/version issues with types and packages.  I knew we were on go version 1.17.2 so it was weird to see references to an older go version that wasn't pointing to the asdf install.
`pkg/services/mocks/SFTPClient.go:6:2: package io/fs is not in GOROOT (/usr/local/Cellar/go@1.14/1.14.7/libexec/src/io/fs)`
Upon further research I saw that my GOROOT was not being set to the asdf go location so I reshimed and updated my GOROOT with `asdf reshim golang && export GOROOT="$(asdf where golang)/go/"`
I am going to add GOROOT to my ~/.zshrc file going forward with the output from asdf as per instructions.

Clarify GOROOT troubleshooting for asdf and don't hardcode env value

---

docs/backend/guides/how-to/create-a-custom-linter.md

In this document I wrote a how-to guide for creating Custom Go linters in MyMove and linked to resources that helped us write our linters. 
-Please leave feedback on how readable this guide is. Are the instructions clear? Is there anything missing?

MB-10168-custom-linter-doc

---

docs/frontend/testing/frontend.md
docs/tools/cicd/happo.md

While @mlm55, @YanZ777, and I were troubleshooting transcom/mymove#7840, we discovered that Knobs don't seem to be supported by Happo on the CI/CD side. So this documentation was updated to help folks not run into the issues that came up during that pairing session.
[=> pairing on Happo](https://ustcdp3.slack.com/archives/C029R9LDTD4/p1638901935175200) 🔒 
[=> the fix that is being referenced in this `caution` admonition](https://github.com/transcom/mymove/pull/7840/commits/4a9fd6bab5a1dcb3143ac7f7c19ecef6e4ca798a)

MB-10110 Better Happo documentation

---

docs/tools/postman/intercepting-cookies-for-postman.md

Updated how the links were formatted because the deployed version requires different absolute paths.

Mb 10777: broken links for postman

---

LICENSE
docs/tutorial/intro.md
docusaurus.config.js
src/components/HomepageFeatures.js
src/components/HomepageFeatures.module.css
src/css/custom.css
src/pages/index.js

I updated the feature page to include some callouts. I consider this work part of migrating away from Docusaurus defaults and making this documentation **MilMove Developer Portal** more production ready.
<details>
<summary>📸  Old homepage screenshot</summary>
</details>
<details>
<summary>📸  New homepage screenshot</summary>
</details>

Update the homepage

---

.github/workflows/test-builds.yml
docusaurus.config.js
src/components/HomepageFeatures.js

The last PR #106  that I merged in broke the build. This PR adds a new Action Workflow to build Docusaurus so that PRs that may break the build don't get merged in. I also refactor the configuration and the homepage to avoid the break in the build that #106 caused due to ES6 import statements.

Fix the build

---

docs/dev/tools/CAC/upload-electronic-orders.md

Updating docs to account for https://github.com/transcom/transcom-infrasec-com/pull/1767 
The other repo in this doc also hasn't been kept up to date, not sure if it should also be archived: [transcom/nom](https://github.com/transcom/nom/)

Add warning about MilMove Orders repo being archived

---

.envrc
nix/default.nix
nix/update.sh

The current nix configuration was failing on my M1 macbook. This PR updates the configuration to work for the latest version of nix and M1 setup.
Should be reviewed by someone using nix.
The following should pass and start docusaurus.
```sh
direnv allow
./nix/update.sh
yarn install
yarn start
```

Update nix setup

---

docs/backend/setup/database-migrations.md

This PR is associated with JIRA ticket [MB-11957](https://dp3.atlassian.net/browse/MB-11957)
Review instruction:
* look at the delete migrations sections and confirm that the instructions are correct.

[ MB-11957 ] update migration docs

---

docs/backend/setup/database-migrations.md

[JIRA ticket](https://dp3.atlassian.net/browse/MB-11996)
This adds/updates information about:
* pluralization of sql table name
* pointers vs not for optional/required fields
* `TableName` function for names that are different from the default generated name
* Adding comments to fields
Also fixed a few links on the page.

MB-11996 update migration docs

---

docs/backend/guides/how-to/upgrade-go-version.md

This updates the list of files that need to be changed as part of a Go upgrade.  This doc has gotten a little out of sync with the current state.

[MB-11991] Update Go upgrade docs

---

docs/backend/guides/how-to/soft-delete.md

Replaced the example query filtering out deleted records with a where clause to use the newer `Scope(utilities.ExcludeDeletedScope())` convenience call.
[Corresponding PR](https://github.com/transcom/mymove/pull/8445) that introduced the ExcludeDeletedScope
To test run:
1. `yarn install` && `yarn start`
2. Visit http://localhost:4000/mymove-docs/docs/backend/guides/how-to/soft-delete

Add ExcludeDeletedScope info and example to soft delete docs

---

docs/api/guides/guide-to-creating-an-endpoint.md

The documentation was referencing `AuditableAppContextFromRequest` instead of `AuditableAppContextFromRequestWithErrors`.

Update creating an endpoint documentation to reflect newer pattern

---

docs/backend/testing/acceptance-testing-syncada-edi-invoicing.md

I noticed some inconsistencies between when I used these instructions and what was written. Here's my attempt at modernizing them a bit more.
A note has been added saying that the tools need to have been built beforehand (thanks @rogeruiz for the suggestion).
The ordering of `Update status of Payment Request` section has been changed since it was confusing to me. I put the payload data before the command to be run. so that it wouldn't be confused with the return payload.
Missing payload data in the `Update stat of Payment Request` has been added to align with my experience.

Add missing body properties and adjust commands

---

.github/dependabot.yml

Noticed we don't have anything to check on our dependencies in this repo

Add a dependabot.yml to keep node and gh action deps up to date

---

docs/adrs/0072-using-react-app-rewired.md
docs/adrs/00XX-using-react-app-rewired.md
vale/Vocab/OSS-Docs/accept.txt

This description was migrated over from https://github.com/transcom/mymove/pull/8751.
When working on updating React-USWDS to the latest version, there were a number of upgrades that needed to be done to the underlying dependencies. This work resulted in the application needing to use a new library called React-App-Rewired in order to apply changes to the configuration for tools used in React-Scripts. This ADR's purpose is to document the decision to not eject the Create-React-App and instead leverage the React-App-Rewired library to modify the webpack configuration.
- transcom/mymove#8713 
- transcom/mymove#8724

[ MB-9033 ] Using React-App-Rewired

---

docusaurus.config.js

I chose to make the light theme a different dark theme because of the
colors we chose for our site and how highlighting lines in code blocks
seems to not work properly due to how the light themes render the dark
selection background.
I specifically chose oceanicNext due to the fact that it fits well with the
MilMove color scheme.

Make light theme oceanicNext

---

.github/CODEOWNERS

I missed this in #156. Sorry y'all.

Fix where the ADR files trigger CODEOWNERS

---

package.json
yarn.lock

We don't use them directly. Seems like they came from when we first set up `docusaurus`, but `docusaurus` lists the right versions it needs as a dependencies, so we don't need to keep up our own version tracking for it.
Replaces #150 and #154

MB-13121 Remove unnecessary direct dependencies

---

docs/backend/guides/ghc/ghc-import-pricing-production.md

When working on MB-13238, we had to setup an ECS task. It was difficult to find
the ECS documentation at first. After finding it, we realized there was a broken
link to this documentation. This patch fixes the issue.

[ MB-13238 ] Link to ECS docs in Confluence

---

utils/redirect-backend.js

This seems to be breaking this link: https://transcom.github.io/mymove-docs/docs/help/index by redirecting it else where.

Removes a redirect for /docs/help

---

docs/tools/docusaurus/redocusaurus.md

This patch series includes some minor house cleaning and some major changes to
how we use the plugin due to upgrades in the Redocusaurus plugin's
configuration. I discovered the need to update this stuff while reviewing work
for MB-13351 transcom/mymove#9118.
- The main reason why this patch series exists.

[ MB-13351 ] Update the Redocusaurus internal documentation

---

docs/backend/setup/database-migrations.md

When the certificate in the demo environment needed a secure migration created recently, we realized the docs weren't as complete as they could be.  They only mentioned the exp, stg, and prd environments and not demo and loadtest, so that's what I've added here.

Mention demo and loadtest environments in secure migrations section

---

docs/backend/testing/run-e2e-tests.md

This work is tied to my volunteer work on the #c-documentation committee. The work is being tracked by @julieclennon in Confluence. This closed the AI around having short documentation on Cypress testing artifacts.

Add Cypress artifacts documentation

---

docs/backend/guides/how-to/upgrade-go-version.md

This PR updates the "How to Upgrade Go Version" page in our docs to reflect the correct list of files that need to be edited with the new docker image hash.

"How to Upgrade Go Version" documentation edits

---

docusaurus.config.js
package.json
yarn.lock

I found that there's another version of the docusearch local plugin - tried it out and lo and behold, it does all the things that seem to be broken on our own version. 
* Searches page titles by search string - I could never find the "Running server tests" page in the current docusaurus but now I can!
* Shows the page title on the search list - helps contextualize when you have a number of identical hits. 
* Provides a "see all results" link to see all the hits instead of just the top few.
Generally it seems to return a lot more results and give a lot more context for the searcher. 
Reviewer: please let me know if there's any other processes to remove one plugin/package with yarn and install another.
Check it out!

Switch search plugin

---

.github/workflows/deploy.yml
.github/workflows/test-builds.yml

We should be using a frozen lockfile when installing dependencies for our CircleCI jobs. 
Using a frozen lockfile will help with detecting if a dependency has been added or removed without updating the lockfile since the job will fail if the correct dependencies are not installed.

Use frozen lockfile when installing dependencies

---

docs/backend/testing/run-go-tests.md

The CircleCI job for running the acceptance tests is being removed.
See [this PR](https://github.com/transcom/mymove/pull/9673) for further details on the removal of the job itself.

Remove the section on acceptance tests

---

docs/about/Home.md

There's a extra bracket that's a typo. This PR removes it.
The auto formatter also decided it wanted to add an extra line between the front matter and the header.

MB-14922 Remove extra bracket

---

README.md
docs/guides/adrs/README.md
docs/guides/adrs/template.md
package.json
scripts/new-adr.sh

This patch adds support for running `npm run new-adr --slug="my-new-adr"` and
have it produce a new ADR file from the template with the suggested front-matter
from the documentation on the ADR guide page. This will help folks contributing
ADRs in the correct way without a whole lot of cognitive overhead.

Adding automation around ADR authoring

---

docs/tools/cicd/github_actions/auto-approve.md

Add documentation for the GitHub Action auto approve.

MB-15044 Add documentation for the GitHub Action Auto Approve

---

docusaurus.config.js
package.json
yarn.lock

Feeling inspired by @yanz777's great work on MB-15044, I found that Docusaurus
has a plugin that brings in the code from a public GitHub repository into
Docusaurus as fenced codeblock. This seems particularly helpful for the intended
reader of this kind of documentation.
Here's an example of how #277 would need to be changed to use this new
codeblock. 
```diff
diff --git a/docs/tools/cicd/github_actions/auto-approve.md b/docs/tools/cicd/github_actions/auto-approve.md
index 6da7e7f6d..d951e35f0 100644
--- a/docs/tools/cicd/github_actions/auto-approve.md
+++ b/docs/tools/cicd/github_actions/auto-approve.md
@@ -2,7 +2,15 @@
+
+
+```yml reference
+https://github.com/transcom/mymove/blob/main/.github/workflows/auto-approve.yml
+```
```
And here's an image preview of the code changes from …

[ MB-15044 ] Add GitHub code blocks to the documentation

---

docs/tools/cicd/github_actions/front-end-linter.md

Add documentation for the purpose and configuration of the front end linter.

MB-15044 Add documentation for the GitHub Action Front End Linter

---

docs/tools/cicd/github_actions/auto-approve.md

feat: Use code block instead of linking to the code for the auto approve documentation

MB-15044 Use Code Block for the Auto Approve Documentation

---

docs/tools/cicd/github_actions/go-auto-approve.md

feat: Add documentation for the GitHub Action go auto approve

MB-15044 Add documentation for the GitHub Action go auto approve

---

docs/about/Welcome.md
docs/about/project-layout.md

Jira ticket [MB-14922](https://dp3.atlassian.net/browse/MB-14922)
This part of ongoing work to reorganize the `Welcome.md` page into more manageable chunks.
The PR pulls out the Project Layout section into its own page.
I'm debating on putting this back into the mymove repo wiki to keep it as close to the code as possible. What do you all think?
[MB-14922]: https://dp3.atlassian.net/browse/MB-14922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MB-14922 reorganize readme project layout

---

docs/tools/cicd/circleci/deploy-app-client-tls.md

feat: Add additional context around the deploy-app-client-tls job.
Adding this documentation was partially driven by our mishaps with updating certificates troubleshooting. This document aims to provide additional context that would be useful, if a similar mishap occurs again. 

MB-15044 Documentation for deploy app client tls

---

docusaurus.config.js

The documentation says this is helpful when wanting the reader to focus
on the documentation. I like it because I have vertical monitors and
appreciate the option to hide the sidebar so I can better read the
content. It also works well to read the documentation on a tablet as
well.

Enable a hideable sidebar

---

docs/adrs/0077-permanently-store-origin-duty-gbloc.md

Transcom needs us to permanently store duty location GBLOC data for MTOs. This ADR addresses the reasoning behind this change including the client's specific requirements and benefits.

MB-15032 - ADR to address storing origin duty GBLOC data

---

docs/about/application-setup/dependencies/pre-commit.md
docs/backend/guides/troubleshoot-precommit-hook-failures.md

- Removes the 2 isolated precommit troubleshooting sections on the `docs/about/application-setup/dependencies/pre-commit.md` page 
- Integrates the removed precommit troubleshooting sections on to the `docs/backend/guides/troubleshoot-precommit-hook-failures.md` page
- Updates the page where the isolated troubleshooting sections were removed to include a link to the consolidated troubleshooting page for precommits

[MB-15308] Consolidate pre-commit troubleshooting issues onto the troubleshooting page

---

docs/backend/setup/database-migrations.md

In [this milmove PR](https://github.com/transcom/mymove/pull/10224), we started including a `TableName` method on every Pop model to avoid potential issues with the way Pop tries to guess the proper table name.  The doc change in this PR attempts to clarify that we do this and why we do it.

Clarify how we use Pop's TableName method

---

docs/backend/guides/how-to/upgrade-go-version.md

This PR adjust the instructions for upgrading golang based on my latest experience in [upgrading to go 1.20.x](https://github.com/transcom/mymove/pull/10185).

Adjust instructions for upgrading golang

---

docs/backend/setup/database-migrations.md

In #312, I updated some documentation about using the `TableName` method in all models and added it to one of the examples on the page.  I inadvertently left `TableName` off of the other model examples on that page, so this PR adds it to them.  I also fixed some tabs vs. spaces whitespace inconsistencies that was throwing off indentation in some markdown renderers.

Added TableName to other Pop model code examples

---

.editorconfig

This was never added to the repository, so I copied it from
`transcom/mymove` and modified it to be more relevant for this codebase.
Discovered in #315.
The added benefit here is that anyone with EditorConfig enabled in their
IDE/PDE, will be able to trim space-characters from the end of any files they
interact with.

[ office-hours ] Adding an update EditorConfig file

---

docs/backend/guides/dtod/testing-dtod.md

Adding a live code-example for `soap.go` rather than only linking to the
library.

[ c-documentation ] Adding live code-example for Soap library

---

README.md

The purpose of this PR is to add sections to the README about testing and updating the documentation so that it informs engineers who may need to make changes to the docs.

MB-15466-Update readme instructions

---

docs/backend/guides/how-to/manage-golang-with-asdf.md

This was brought up by @ruizajtruss while troubleshooting his
environment. These changes help get unstuck and are more generic across
different Apple chip installations. There is also an updated comment
which is explicit about the order of operations when it comes to loading
`asdf.sh` and the subsequent `go env` commands.

Updating the `asdf` troubleshooting documentation

---

docusaurus.config.js
sidebars.js

Added a link to the v2 API docs and added a second link to the v1 docs for url consistency.

MB-16460: Add link to prime v2 docs

---

docs/adrs/0082-use-flipt-feature-flags.md

Renaming the ADR so that there aren't title and numbering conflicts.

Rename file for consistency

---

docs/backend/guides/how-to/upgrade-go-version.md

As a follow on to https://github.com/transcom/mymove/pull/11126, we need to make sure the docs referencing .go-version are updated. 
Fortunately that was only one place, so this PR removes instructions to update `.go-version` when upgrading the Go version, as it was removed from the repo.

Remove documentatation references to .go-version

---

docs/frontend/guides/how-we-use-react-router.md

This PR is a first pass at getting documentation around how we use (and test) react-router. I tried to describe and provide examples of patterns and related utilities. I hope to eventually add a bit more in the testing section but this seemed complete enough to move forward with a PR. 
I was able to run with: `bash <(curl -s https://raw.githubusercontent.com/monfresh/fresh-brew/main/fresh-press)`. if that doest work check out the readme https://github.com/transcom/mymove-docs/blob/main/README.md

Add 'how we use react-router' doc

---

docs/backend/testing/running-integration-tests-with-routing-middleware-enabled.md

This adds documentation according to [this ticket](https://dp3.atlassian.net/browse/MB-16873), and based on existing integration tests that follow some of this pattern. 
Instructions for building the request body are based on conclusions reached in A-Team's meandering sync and the BE/FE check-in: prefer the use of existing types to leverage Intellisense and compile-time errors, as opposed to using raw strings as JSON or locally-typed objects.

MB-16873 - Add documentation for server integration tests using middleware.

---

docs/backend/guides/how-to/upgrade-node.md

Added some troublshooting steps to use when having issues upgrading nodejs

added troubleshooting to upgrade node docs
