- docs/dev/tools/docusaurus.md
👀 [See this Slack message here](https://ustcdp3.slack.com/archives/C027BDJ4678/p1632440193109200?thread_ts=1632434266.107200&cid=C027BDJ4678)🔒 for more context around this PR.
> Putting documentation here rather than Slack

- .envrc
- .gitignore
- README.md
- nix/default.nix
- nix/update.sh
Since Nix has proven useful on other projects, I thought I'd add it as an
option here. I plan on submitting a separate PR that automates much of
the manual setup for both the Nix and Brew options via a shell script.﻿
> Add Nix setup and improve README instructions

- docs/dev/testing/test-data/Test-Data-Generation.md
This was brought up in Slack and I took it upon myself to update the layout so it would be more legible. I missed this the first time I read through the documentation.
> Update Test Data Generation docs around Ephemeral environments

- docs/frontend/guides/how-to-store-api-data-on-the-front-end.md
- docs/frontend/guides/store-data-in-redux.md
- utils/redirect-frontend.js
~~This only changes the title and does not change the URL. We could change the URL too, but then would need to add a client-side redirect.~~
After talking to @donaldthai we agreed that adding Redirects and Renaming the URL would be the better choice.
> MB-9806 Rename docs title

- docs/frontend/guides/how-we-use-react-query.md
ℹ️ Pairing with @donaldthai on this. 
This is part of the work for _Application configuration guide: Additional documentation for Front-end best practices_ in Jira https://dp3.atlassian.net/browse/MB-9806 🔒
> MB-9806 Add React Query brief primer and best practices

- docs/frontend/setup/designers-guide-to-setting-up-app-locally.md
These changes are related to [ticket 9798](https://dp3.atlassian.net/browse/MB-9798). It adds a few more lines of context for environment variables and adds the system requirements for the project
> kc-mb-9798 - Update getting started designers

- docs/backend/guides/how-to/add-an-event-trigger.md
Add reference to how to test notifications
> Add reference to how to test notifications

- docs/tools/postman/intercepting-cookies-for-postman.md
Fix formatting and broken links to screenshots
> MB-10777 Fix broken links for postman setup

- docs/tools/dependabot/dependency-update-process-with-dependabot.md
- docs/tools/dependabot/manage-dependabot.md
Corresponding changes to adding Dependabot configuration to the transcom/milmove_load_testing repo https://github.com/transcom/milmove_load_testing/pull/98
> [MB-10562] Update dependabot links to reflect annexation into GitHub

- docs/vault/[deprecated]-run-loki-tests-against-storybook.md
> [vale] Review docs Deprecated Run Loki Tests

- docs/help/Troubleshoot-CAC-Reader-Issues.md
> [vale] Review docs Troubleshoot CAC Reader Issues

- docs/frontend/testing/frontend.md
> [vale] Review docs Testing Frontend

- docs/frontend/setup/run-storybook.md
> [vale] Review docs Running Storybook

- docs/dev/testing/running-tests/Manually-run-Prime-API-for-Slice-demo.md
> [vale] Review docs Manually Run Prime API for Slice Demo

- docs/backend/setup/using-eagerpreload-in-pop.md
> [vale] Review docs Eagerpreload in Pop

- docs/backend/guides/how-to/set-up-a-feature-flag.md
> [vale] Review docs Set Up a Feature Flag

- docs/backend/guides/database.md
> [vale] Review docs Database

- docs/backend/guides/ghc/ghc-import-pricing-production.md
> [vale] Review docs GHC Import Pricing Production

- docs/backend/guides/ghc/ghc-invoicing.md
> [vale] Review docs GHC Invoicing

- docs/backend/guides/golang-loops.md
> [vale] Review docs Golang Loops

- docs/backend/guides/backend-structure.md
> [vale] Review docs Backend Structure

- docs/api/guides/guide-to-creating-an-endpoint.md
> [vale] Review docs Creating an Endpoint

- docs/api/guides/api-programming-guide.md
> [vale] Review docs API Programming Guide

- docs/about/security/dmdc-identity-web-services.md
> [vale] Review docs DMDC security page

- docs/about/security/dod-certs.md
> [vale] Review docs DOD Certs

- docs/about/security/user-management.md
> [vale] Review docs User Management

- docs/dev/tools/CAC/Using-your-CAC-in-Browsers-on-MacOS.md
> [vale] Review docs CAC in Browsers on macOS

- docs/api/docs/push-notifications-to-prime.md
> [vale] Review docs Push Notifications to Prime

- docs/api/testing/acceptance-testing-prime-api-endpoints.md
> [vale] Review docs Acceptance Testing Prime API Endpoints

- docs/api/testing/end-to-end-testing-playing-the-prime.md
> [vale] Review docs End to End Testing Playing the Prime

- docs/backend/guides/how-to/create-a-custom-linter.md
> [vale] Review docs Create a Custom Linter

- docs/backend/guides/tspp-data-creation.md
> [vale] Review docs TSPP Data Creation

- docs/backend/guides/switching-over-to-nix.md
> [vale] Review docs Switching over to Nix

- docs/backend/guides/session-management.md
> [vale] Review docs Session Management

- docs/backend/guides/open-telemetry.md
> [vale] Review docs Open Telemetry

- docs/backend/guides/how-to/upgrade-node.md
> [vale] Review docs Upgrade Node

- docs/backend/guides/guide-to-static-analysis-annotations-for-disabled-linters.md
> [vale] Review docs Static Analysis Annotations for Disabled Linters

- docs/backend/guides/golang-time.md
> [vale] Review docs Golang Time

- docs/backend/guides/access-global-variables.md
> [vale] Review docs Access Global Variables

- docs/tools/locust/running-load-tests.md
- docusaurus.config.js
- package.json
- yarn.lock
This PR adds Mermaid diagram support using code blocks. Similar to GitHub, we're able to add them as code blocks.
<pre><code>
```mermaid
flowchart LR
a-->b
b--->c
b-->a
```
</code></pre>
```mermaid
flowchart LR
a-->b
b--->c
b-->a
```
> Add Mermaid diagram support

- docs/backend/guides/database.md
> Updating database.md to fix all database links

- docs/backend/testing/run-e2e-tests.md
This documentation helped me while getting things setup when testing transcom/mymove#8240.
> [ MB-11826 ] Better Cypress docs

- docusaurus.config.js
- sidebars.js
This was suggested by @mboren for ease of use. I agreed and used my on-call duties to help facilitate this. These docs are already public so I do not see the harm in adding them in to our public documentation. But please feel free to review these changes locally.
> [ MB-11902 ] Add in the other APIs

- docs/api/guides/guide-to-creating-an-endpoint.md
This was brought up in https://github.com/transcom/mymove/pull/8304#discussion_r833411905. I'm placing it in the documentation as part of the work for MB-11958 so that we can keep track why this refactor is being done.
> [ MB-11958 ] Add some additional information about transactions

- docs/backend/guides/roles-and-permissions.md
Pretty self explanatory, wanted to get some initial docs down for this work.
> Adding docs for roles and permissions

- .github/workflows/deploy.yml
I missed this in #155 when I was updating other dependencies.
> Upgrade node for the deployment

- docs/backend/testing/running-server-tests-inside-a-transaction.md
Update docs for RunWithPreloadedData.
> Updated for RunWithPreloadedData

- docs/backend/testing/run-go-tests.md
This has come up during the MB-11967 ticket. We're making the Go test
documentation better together.
Pairing with @mmayo-truss on this. Currently this is a work in progress with
more updates to this description coming in the future.
> [ MB-11967 ] Update documentation for running Go tests

- docs/adrs/0073-using-templates-for-sql-queries.md
- docs/adrs/00XX-using-templates-for-sql-queries.md
Research and compare options for SQL template architecture in MilMove to improve the developer experience of writing SQL queries and to open opportunities for SQL linting/checking.
> MB-12577 SQL templating ADR

- docs/adrs/0073-using-templates-for-sql-queries.md
Updated the existing ADR for SQL templating to account for discoveries made during initial implementation and to better capture the final direction taken.
> Update ADR 0073 to record implementation findings

- docs/frontend/testing/using-factories-to-generate-data-for-frontend-tests.md
I didn't want to commit directly to your PR so just thought I would make a PR to fix some minor edits.
> Update minor syntax related items

- docs/frontend/testing/writing-tests-using-react-testing-library-and-jest.md
This documents the high-level preference of `userEvent` over `fireEvent`, and performance considerations of different `userEvent`s.
> Adds documentation about userEvents

- docs/frontend/testing/writing-tests-using-react-testing-library-and-jest.md
userEvent was updated to 14.4.3 in [this PR](https://github.com/transcom/mymove/pull/9086). It now returns a promise, so this small update reflects that change.
> update language to reflect userEvent returning a promise

- docs/backend/guides/understanding-milmove-routing.md
Add an article that describes how the routing on MilMove is set up.
> Add article on understanding milmove routing

- docs/about/Welcome.md
[Jira ticket](https://dp3.atlassian.net/browse/MB-10301)
Created a new file inside of the About page that is a straight migration of [the README.md inside of the mymove repo](https://github.com/transcom/mymove/blob/main/README.md). 
Organizing the readme better will be a series of separate PRs and not covered in this one.
There will be a separate PR inside the mymove repo to remove most of the contents of the README.
Please merge before [#9882](https://github.com/transcom/mymove/pull/9882)
> MB-10301 Migrate the readme from the mymove repo over into this repo

- docs/about/Welcome.md
- docs/about/supported-browsers.md
Jira ticket [MB-14922](https://dp3.atlassian.net/browse/MB-14922)
This part of ongoing work to reorganize the `Welcome.md` page into more manageable chunks.
The PR pulls out the Supported Browsers section into its own page.
[MB-14922]: https://dp3.atlassian.net/browse/MB-14922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MB-14922 reorganize readme supported browsers

- docs/backend/guides/understanding-milmove-routing.md
Incorporated some feedback from #252. 
Fix some grammatical errors.
Add brief definition on routing.
Clarify the example around the index handler.
> Add some feedback on the MilMove Routing Docs

- docs/tools/cicd/github_actions/happo-tests-main.md
- docs/tools/cicd/github_actions/happo-tests.md
feat: Add documentation for both the GitHub Actions that run Happo
> MB-15044 Document the GitHub Actions for Happo

- README.md
- docs/about/application-setup/base-setup/homebrew.md
- docs/about/application-setup/setup-manually/prerequisites.md
The README was very heavily reorganized. PR #286 makes changes to the unorganized version. This attempts to incorporate those changes into the recently reorganized and broken down README.
fix: Various links needed to be relinked for fresh brew
fix: Add some additional context around installation
> Fix various broken links for fresh brew

- docs/backend/guides/dtod/_category_.json
- docs/backend/guides/dtod/dtod-architecture.md
- docs/backend/guides/dtod/index.md
- docs/backend/guides/dtod/testing-dtod.md
Add new documentation about DTOD's architecture in the code and how to test it.
Information has mainly been pulled from these sources
This is an oncall incident that has useful information inside of the thread.
https://ustcdp3.slack.com/archives/CP4U2NKRT/p1677180784605049
This is a coalescence of information pulled into one page.
https://dp3.atlassian.net/wiki/spaces/~257884539/pages/2084569214/DTOD+Digging
> MB-15567 Discovery: How does our integration with DTOD work

- docs/backend/guides/tget/_category_.json
- docs/backend/guides/tget/index.md
https://dp3.atlassian.net/browse/MB-15649
Add developer documentation for TGET and what we have now
> MB-15649 Discovery TGET integration

- docs/frontend/guides/using-modals.md
Add documentation for how to use modals.
> MB-15819 Documentation on Modals

- docs/adrs/0078-api-versioning.md
- docs/adrs/0079-api-versioning.md
[JIRA Ticket](https://dp3.atlassian.net/browse/MB-15994)
This ADR is addressing the technical approach for Versioning our Prime API. It is partnered with [this draft policy Doc](https://dp3.atlassian.net/wiki/spaces/MT/pages/2147188743/Draft+Prime+API+Versioning+Policy).
I have also created a test PR of possible approaches for versioning our api. I added one version 2 of the List Prime Moves endpoint. [It can be found here](https://github.com/transcom/mymove/pull/10816).
A lot of what we decide will really be more of a social compact than anything outright technical. Which approach would be best suited for how we will work together on the multiple versions of the API as a team?
> [ MB-15994 ] Prime API Versioning ADR

- docs/backend/testing/run-go-tests.md
> Update examples in the Go Testing guide

- docs/about/application-setup/01-base-setup/02-git.md
Some updates from @mandaem going through application setup again
> Tweak setup docs

- docs/integrations/gex/index.md
https://dp3.atlassian.net/browse/MB-12698
Document was in draft and has now been renamed, so the URL needs to be updated.
> Update GEX documentation

- docs/getting-started/development/README.md
- docs/getting-started/development/_category_.json
- docs/getting-started/okta/00-okta-overview.md
- docs/getting-started/okta/01-okta-admins.md
- docs/getting-started/okta/02-csv-import.md
- docs/getting-started/okta/03-okta-troubleshooting.md
- docs/getting-started/okta/README.md
- docs/getting-started/okta/_category_.json
Please look over these docs and let me know if you have any questions. You can check out the code locally by running `yarn start` after navigating into the repo following branch pull.
> updating okta docs

- docs/frontend/guides/how-to-add-move-history-events.md
documentation for adding events to the audit_history table and our MoveHistory component
> add move history event docs

- docs/backend/guides/feature-flags-in-the-app.md
- docs/backend/guides/how-to/add-an-experimental-feature-flag.md
- docs/backend/guides/how-to/revert-a-change.md
- docs/backend/guides/how-to/set-up-a-feature-flag.md
- docs/backend/guides/how-to/soft-delete.md
- docs/backend/guides/how-to/upgrade-go-version.md
- docs/backend/guides/how-to/upgrade-node.md
- docs/frontend/guides/set-up-a-feature-flag.md
- docs/tools/feature-flags/how-to-use-feature-flags.md
- utils/redirect-backend.js
[B-18310](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A873911)
This pull request adds documentation for the experimental backend feature flag `EnvFetcher`.
> B-18310 experimental feature flag documentation with EnvFetcher

- docs/frontend/guides/set-up-a-feature-flag.md
Added documentation for method of accessing feature flags on the frontend without use of context.
> added detect flags method documentation

- docs/tools/feature-flags/how-to-use-feature-flags.md
> quick doc fix

- docs/getting-started/development/multiple-independent-branches.md
This doc update is associated with the makefile update in [this PR](https://github.com/transcom/mymove/pull/12008)
> added documentation for new makefile command multi_branch

- docs/getting-started/application-setup/06-run-the-app.md
update for the additional entries which are in the /etc/hosts file
> hosts-file-config-update

- docs/integrations/tget/index.md
- docs/integrations/tget/trdm-lambda.md
Enhancing TGET TRDM docs per [B-19140](https://www13.v1host.com/USTRANSCOM38/story.mvc/Summary?oidToken=Story%3A922333) completion.
> enhanced documentation

- docs/tools/feature-flags/how-to-use-feature-flags.md
removed old documentation for creating a function to check FF in featureFlag.js because there's a function to check any feature flag now.
> updated docs for frontend feature flag creation

- docs/tools/feature-flags/how-to-use-feature-flags.md
I forgot to include the class component changes 🙃
> updated class component FF doc

- docs/tools/feature-flags/how-to-use-feature-flags.md
added instructions for mocking feature flags
> FF added jest testing instruction

- package.json
- yarn.lock
Reverts transcom/mymove-docs#497
> Revert "build(deps): Bump eslint from 8.54.0 to 9.2.0"

- docs/getting-started/okta/04-okta-emails.md
Adding page to docs for how to use VTL in Okta emails, including an example of implementation for [E-06018](https://www13.v1host.com/USTRANSCOM38/assetdetail.v1?number=E-06018).
https://github.com/user-attachments/assets/1e50c64c-b02a-49c1-b142-30adaec0d7c9
> E-06018 Okta Email VTL Docs

- package.json
- yarn.lock
Reverts transcom/mymove-docs#520
> Revert "build(deps): Bump eslint from 8.54.0 to 9.9.1"

- docs/tools/cicd/circleci/known-local-limitations.md
Please see https://github.com/transcom/trdm-lambda/pull/18 for more details
> Document CircleCI Limitations
